marks/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('about-us', views.about, name='about'),
    path('login', views.signin, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.signout, name='logout'),
    path('help', views.help_view, name='help'),
    path('account', views.account, name='account'),
    path('trade', views.trade, name='trade'),
    path('shop', views.shop, name='shop'),
    path('note', views.note, name='note'),
    path('chats', views.chats, name='chats'),
    path('favorites', views.favourites, name='favorites'),
    path('my_products', views.my_products, name='my_products'),
    path('my_orders', views.my_orders, name='my_orders'),
    path('news/<int:news_id>', views.news, name='news'),
    path('product/<int:product_id>', views.product, name='product'),
    path('yields/<int:yield_id>', views.yields , name='yields'),
    path('order/<int:yield_id>', views.order , name='order'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('favorite/<int:product_id>', views.favorite, name='favorite'),
    path('favorite_for_yields/<int:yield_id>', views.favorite_for_yields, name='favorite_for_yields'),
    path('chat/<str:username>', views.chat, name='chat'), 
    path('product/<int:pk>/update', views.ProductUpdateView.as_view(), name='product-update'),
    path('product/<int:pk>/delete', views.ProductDeleteView.as_view(), name='product-delete'),
    path('user/<int:pk>/delete', views.UserDeleteView.as_view(), name='user-delete'),
    path('favorite/<int:pk>/delete', views.FavoriteDeleteView.as_view(), name='favorite-delete'),
    path('order/<int:pk>/update', views.OrderUpdateView.as_view(), name='order-update'),
    path('order/<int:pk>/delete', views.OrderDeleteView.as_view(), name='order-delete')
]

marks/marks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marks/main/models.py
from asyncio import SendfileNotAvailableError
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone
from django.contrib.auth.models import User


class Review(models.Model):
    task = models.TextField('Reviews')
    stars = models.PositiveSmallIntegerField('Stars', validators=[MinValueValidator(1), MaxValueValidator(5)])
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.task

    def stars_range(self):
        """ Used in templates to render self.stars number of stars """
        return range(self.stars)

    class Meta:
        constraints = [
            models.CheckConstraint(
                name='valid_stars_range',
                check=models.Q(stars__gt=0) & models.Q(stars__lt=6)
            ),
        ]


class News(models.Model):
    news = models.TextField()
    description = models.TextField()
    source = models.CharField(max_length=30)
    imagenews = models.ImageField(upload_to='products/')

    def __str__(self):
        return self.news


class Comment(models.Model):
    comment = models.TextField()
    news = models.ForeignKey(News, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.comment)


class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=15)
    description = models.TextField()
    price = models.PositiveIntegerField()
    image_1 = models.ImageField(upload_to='products/')
    image_2 = models.ImageField(upload_to='products/', null=True, blank=True)
    image_3 = models.ImageField(upload_to='products/', null=True, blank=True)
    image_4 = models.ImageField(upload_to='products/', null=True, blank=True)
    image_5 = models.ImageField(upload_to='products/', null=True, blank=True)
    image_6 = models.ImageField(upload_to='products/', null=True, blank=True)

    def get_absolute_url(self):
        return f'/account'

    def __str__(self):
        return self.name
    

class Yield(models.Model):
    name = models.CharField(max_length=15)
    description = models.TextField()
    price = models.PositiveIntegerField()
    image_1 = models.ImageField(upload_to='products/', null=True, blank=True)
    image_2 = models.ImageField(upload_to='products/', null=True, blank=True)
    image_3 = models.ImageField(upload_to='products/', null=True, blank=True)
    image_4 = models.ImageField(upload_to='products/', null=True, blank=True)
    image_5 = models.ImageField(upload_to='products/', null=True, blank=True)
    image_6 = models.ImageField(upload_to='products/', null=True, blank=True)

    def get_absolute_url(self):
        return f'/account'

    def __str__(self):
        return self.name


class Offer(models.Model):
    price = models.PositiveIntegerField()
    product = models.ForeignKey(Product, related_name='offers', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.price)


class Favorite(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    yields = models.ForeignKey(Yield, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class ReviewOfUser(models.Model):
    task = models.TextField('Reviews')
    rating = models.PositiveIntegerField()
    profile_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='profile_user', on_delete=models.CASCADE)
    comment_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comment_user', on_delete=models.CASCADE)


    def __str__(self):
        return str(self.profile_user)

    def rating_range(self):
        return range(self.rating)

    class Meta:
        constraints = [
            models.CheckConstraint(
                name='valid_rating_range',
                check=models.Q(rating__gt=0) & models.Q(rating__lt=6)
            ),
        ]

class Message(models.Model):
    text = models.TextField()
    created_at = models.DateTimeField('created', default=timezone.now, blank=True)
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='sent_messages', on_delete=models.CASCADE)
    recipient = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='received_messages', on_delete=models.CASCADE)
    
    def datepublished(self):
            return self.created_at.strftime('%T')


    class Meta:
        constraints = [
            models.CheckConstraint(
                name="prevent_self_message",
                check=~models.Q(sender=models.F('recipient'))
            )
        ]


class Order(models.Model):
    yields = models.ForeignKey(Yield, on_delete=models.CASCADE)
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    pnumber =  models.PositiveBigIntegerField('Phone number')
    adress = models.TextField()

    def get_absolute_url(self):
        return f'/account'

    def __str__(self):
        return str(self.customer)
    
# class Avatar(models.Model):
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     image = models.ImageField(upload_to='avatars/')

#     def __str__(self):
#         return str(self.user)

class Profile_Of_User(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    avatar = models.ImageField(default='default.png', upload_to='avatars/', null=True, blank=True)
    bio = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.user.username

marks/main/forms.py
from .models import Message, Review, Product, News, Offer, Comment, ReviewOfUser, Order, Profile_Of_User
from django.forms import ModelForm, TextInput, Select, TextInput, FileInput
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ["task", "stars"]
        widgets = {
            "task": TextInput(attrs={
                'class': 'form-control fields',
            }),
            "stars": Select(choices=[(str(star), star) for star in range(1, 6)], attrs={
                'class': 'form-control'
            }),
        }

class ReviewProfileForm(ModelForm):
    class Meta:
        model = ReviewOfUser
        fields = ["task", "rating"]
        widgets = {
            "task": TextInput(attrs={
                'class': 'form-control fields',
                'placeholder': 'Введите свой отзыв'
            }),
            "rating": Select(choices=[(str(star), star) for star in range(1, 6)], attrs={
                'class': 'form-control fields'
            }),
        }


class Profile_Of_Form(ModelForm):
    class Meta:
        model = Profile_Of_User
        fields = ["bio", "avatar"]
        widgets = {
            "bio": TextInput(attrs={
                'class': 'form-control',
            }),
            "avatar":  FileInput(attrs={
                'class': 'form-control'
            }),
        }


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description", "price", "image_1", "image_2", "image_3", "image_4", "image_5", "image_6"]
        widgets = {
            "name": TextInput(attrs={
                'class': 'form-control',
            }),
            "description": TextInput(attrs={
                'class': 'form-control fields',
            }),
            "price": TextInput(attrs={
                'class': 'form-control',
            }),
            "image_1": FileInput(attrs={
                'class': 'form-control',
            }),
            "image_2": FileInput(attrs={
                'class': 'form-control',
            }),
            "image_3": FileInput(attrs={
                'class': 'form-control',
            }),
            "image_4": FileInput(attrs={
                'class': 'form-control',
            }),
            "image_5": FileInput(attrs={
                'class': 'form-control',
            }),
            "image_6": FileInput(attrs={
                'class': 'form-control',
            }),
        }


class YieldForm(ModelForm):
    class Meta:
        model = Order
        fields = ["pnumber", "adress"]
        widgets = {
            "pnumber": TextInput(attrs={
                'class': 'form-control fields',
            }),
            "adress": TextInput(attrs={
                'class': 'form-control fields',
            }),
        }


class OfferForm(ModelForm):
    class Meta:
        model = Offer
        fields = ["price"]
        widgets = {
            "price": TextInput(attrs={
                'class': 'form-control',
                'placeholder': '   Ваш оффер'
            })
        }

# class AvatarForm(ModelForm):
#     class Meta:
#         model = Avatar
#         fields = ["image"]
#         widgets = {
#             "image": FileInput(attrs={
#                 'class': 'form-control',
#             })
#         }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["comment"]
        widgets = {
            "comment": TextInput(attrs={
                'class': 'form-control fields',
                'placeholder': 'Введите свой комментарий'
            })
        }


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['text']
        widgets = {
            "text": TextInput(attrs={
                'class': 'form-control searchmessage',
                'placeholder': 'Введите текст сообщения'
            })
        }

class AccountCreationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class':('form-control')})
        self.fields['password1'].widget.attrs.update({'class':('form-control')})        
        self.fields['password2'].widget.attrs.update({'class':('form-control')})

class SigninForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class':('form-control')})
        self.fields['password'].widget.attrs.update({'class':('form-control')})     

marks/main/templates/main/about.html
{% extends 'main/base.html' %}

{% block title %}
Отзывы
{% endblock %}

{% block content %}
<h1 class="display-4 fw-normal text-center mt-4">О нас</h1>
<div class="text-center">
    <p class="fs-5 text-muted">Сдесь вы можете посмотреть наши отзывы и оствить свой! </p>
    <div class="text-center text-white rounded bg-dark" style="margin-bottom: 25px;">
        <h4 style="padding: 30px; color: white;">Наша средняя оценка  {{ average }}★</h4>
    </div>
</div>
    {% if page %}
        {% for review in page %}
            <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
                <h3>{{ review.user }}:</h3>
                <h4 class="fs-5 text-muted">{{ review.task }}</h4>
                <h3>Оценка:</h3>
                <h4 class="fs-5 text-muted">
                    {% for _ in review.stars_range %}★{% endfor %}
                </h4>
            </div>
        {% endfor %}

            {% if page.has_previous %}
                <a href="?page=1" class="pinkbutton my-2 mb-2">Первая страница</a>
                <a href="?page={{ page.previous_page_number }}" class="pinkbutton my-2 mb-2">Предыдущщяя</a>
            {% endif %}
            {% if page.has_next %}
                <a href="?page={{ page.next_page_number }}" class="pinkbutton my-2 mb-2">Следующая</a>
                <a href="?page={{ page.paginator.num_pages }}" class="pinkbutton my-2 mb-2">Поледняя страница</a>
            {% endif %}

            <span class="fs-5 text-muted">Страница {{ page.number }} из {{ page.paginator.num_pages }}</span><br><br>
    {% else %}
        <p class="fs-5 text-muted">Да, много сегодня отзывов</p>
    {% endif %}

    {% if user.is_authenticated %}
        <form method="post" class="">
            {% csrf_token %}
            <h2 class="display-6 fw-normal text-center">Твой отзыв:</h2><br>
            <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
                {% for field in form %}
              <div>
                  {{ field }}<br>
              </div>
            {% endfor %}
            <button type="submit" class="pinkbutton mt-1 mb-1">Добавить</button>
            </div>
        </form>
    {% else %}
        <p1 class="fs-5 text-muted">Вы не вошли в аккаунт</p1><br><br>
        <a href="register" class="pinkbutton me-2 mb-2">Зарегестрируйся, и оставь свой отзыв</a><br><br>    
    {% endif %}
{% endblock %}

{% block content2 %}

{% endblock %}

marks/main/templates/main/account.html
{% extends 'main/base.html' %}

{% block title %}
аккаунт
{% endblock %}

{% block content %}
    <h1 class="display-4 fw-normal text-center mt-4">{{ request.user.username }}</h1><br>
    {% if profile_of_user.bio %}
    <div class="text-center text-white rounded bg-dark" style="margin-bottom: 25px; min-height: 130px;">
        <img src="{{ profile_of_user.avatar.url }}" class="avatar" width="75" height="75" style="float: left;"/>
        <p style="float: left;" class="fs-5 text-muted bio">{{profile_of_user.bio}}</p><br><br>
    </div>
    {% endif %}
    <h4 class="display-6 fw-normal text-center my-3">Товары и заказы</h4><br>

    <div class="parent">

    {% if page %}
        <div class="p-4 p-md-5 mb-4  rounded bg-dark d-flex">
            <a class="display-6 text-white fw-normal account" style="padding: 2.75rem 0;" href="{% url 'favorites' %}">Избранные товары</a>
            <div style="margin-left: auto;">
                {% for favorite in favorites %}
                    {% if favorite.product.name %} 
                        <img src="{{ favorite.product.image_1.url }}" width="150" height="150" style="margin-left: 50px;" />
                    {% endif %}
                    {% if favorite.yields.name %}
                        <img src="{{ favorite.yields.image_1.url }}" width="150" height="150" style="margin-left: 50px;" />
                    {% endif %}
                {% endfor %}
            </div>
        </div>

    {% else %}
    <div class="text-center">
        <a href="{% url 'trade' %}" class="pinkbutton text-center">В избранном пусто! Скорее за покупками🤠</a><br>
    </div><br>
    {% endif %}

    <!-- <h4 class="display-6 fw-normal text-center my-3">Мои товары</h4><br> -->
    
    {% if products %}
    
    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark d-flex">
        <a class="display-6 fw-normal text-white account" style="padding: 2.75rem 0;" href="{% url 'my_products' %}">Мои товары</a>  
        <div style="margin-left: auto;">
            {% for product in products %}
                <img src="{{ product.image_1.url }}" width="150" height="150" style="margin-left:50px;" />
            {% endfor %}
        </div>
    </div>
    {% else %}
    <div class="text-center">
    <a href="{% url 'trade' %}" class="pinkbutton">Скорее выложете свой первый товар! 👟</a><br>
    </div><br>
    {% endif %}
    
    <!-- <h4 class="display-6 fw-normal text-center">Мои заказы</h4><br> -->

    {% if orders %}
        <div class="p-4 p-md-5 mb-4  rounded bg-dark d-flex">
            <a class="display-6 text-white fw-normal account" style="padding: 2.75rem 0;" href="{% url 'my_orders' %}">Мои заказы</a>
            <div style="margin-left: auto;">
                {% for order in orders %}
                    <img src="{{ order.yields.image_1.url }}" width="150" height="150" style="margin-left:50px;" />
                {% endfor %}
            </div>
        </div>
    {% else %}
        <div class="text-center">
            <a href="{% url 'shop' %}" class="pinkbutton text-center">Заказы отсутствуют! Скорее за покупками🤠</a><br>
        </div><br>
    {% endif %}

    </div>

    <h4 class="display-6 fw-normal text-center">Мои отзывы</h4><br>

    <div class="text-center text-white rounded bg-dark" style="margin-bottom: 25px;">
        <h4 style="padding: 30px; color: white;">Твоя репутация  {{ average }}★</h4>
    </div>
    {% if page_ %}
        {% for profile_ in page_ %}
            <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
                <h3>{{ profile_.comment_user }}:</h3>
                <h4 class="fs-5 text-muted">{{ profile_.task }}</h4>
                <h3>Оценка:</h3>
                <h4 class="fs-5 text-muted">
                    {% for _ in profile_.rating_range %}★{% endfor %}
                </h4>
            </div>
        {% endfor %}

            {% if page_.has_previous %}
                <a href="?page=1" class="pinkbutton my-2 mb-2">Первая страница</a>
                <a href="?page={{ page.previous_page_number }}" class="pinkbutton my-2 mb-2">Предыдущщяя</a>
            {% endif %}
            {% if page_.has_next %}
                <a href="?page={{ page.next_page_number }}" class="pinkbutton my-2 mb-2">Следующая</a>
                <a href="?page={{ page.paginator.num_pages }}" class="pinkbutton my-2 mb-2">Поледняя страница</a>
            {% endif %}

            <span class="fs-5 text-muted">Страница {{ page_.number }} из {{ page_.paginator.num_pages }}</span><br><br>
    {% else %}
    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
        <h4>У тебя отсутствуют отзывы 👤</h4>
    </div>
    {% endif %}

    {% if profile_of_user.bio %}
        <h4 class="display-6 fw-normal text-center">Редактирование профиля</h4><br>
    {% else %}
        <h4 class="display-6 fw-normal text-center">Заполните свой профиль</h4><br>
    {% endif %}
    <div class="text-center text-white rounded bg-dark" style="margin-bottom: 25px; min-height: 130px;">
        <p style="padding-top: 30px;" class="fs-5 text-muted text-center">Выберите аватар</p>
        <form method="post" enctype="multipart/form-data" class="">
            {% csrf_token %}
            <div class="avatar_form">{{ profile_form.avatar }}</div>
            <p class="fs-5 text-muted text-center">Введите описание профиля</p>
            <div class="bio_form">{{ profile_form.bio }}</div>
            <div class="d-flex">
                <button style="margin-left: 30px; margin-bottom: 30px;" name="profile_form" type="submit" class="pinkbutton">Сохранить</button>
            </div>
        </form>
    </div>
    <div class="d-flex">
        <form action="{% url 'logout' %}" method="POST">
            {% csrf_token %}
            <div class="text-center">
                <button type="submit" class="pinkbutton">Выйти из аккаунта</button>
            </div>
        </form>
        <a style="margin-left: 30px;" class="pinkbutton" href="{% url 'user-delete' request.user.id %}">Удалить аккаунт</a>
    </div>
{% endblock %}
{% block content2 %}

{% endblock %}

marks/main/templates/main/chats.html
{% extends 'main/base.html' %}

{% block title %} главная {% endblock %} 
{% block content %} 
<div class="d-flex">
    <div class="listofchats">
        <h1 class="mt-2">Твои чаты</h1>
        {% if users %}
            {% for user in users %}
            <div class=" text-white rounded bg-dark" style="margin-bottom: 15px; margin-right: 70px; padding: 8px;">
                <a href="{% url 'chat' user.username %}" style="color: white; margin-bottom: 15px;" class="lead my-3 px-2 link-dark text-decoration-none mb-2 mt-2 messagetag">{{user.username}}</a>
                <p style="color: rgb(156, 156, 156);">{{chat__messages.text}}</p>
            </div>
            {% endfor %}
        {% else %}    
            <div class="text-center text-white rounded bg-dark" style="margin-bottom: 15px; margin-right: 70px; padding: 8px;">
                <p>У тебя отсутствуют чаты. Переходи на рынок и найди продовца или продай свой товар 👥</p>
            </div>
            <a href="{% url 'trade' %}" style="margin-bottom: 15px;" class="pinkbutton mb-1">В магазин</a>
        {% endif %}
            
    </div>
    <div class="line"></div>
    <div class="chat">
        {% block content3 %}{% endblock %}
    </div>
{% endblock %}

{% block content2 %}
{% endblock %}

marks/main/templates/main/delete.html
{% extends 'main/base.html' %} 

{% block title %}Удаление брони{% endblock %}

{% block content %}
        <h3 class="display-7 fw-normal text-center mb-3">Вы точно хотите удалить ваш товар?</h3>
        <div class="d-flex">
            <form method="post" class="yes_form">
                {% csrf_token %}
                <button class="redbutton" type="submit">Да</button>
                <a href="{% url 'account' %}" style="padding: 10px;" class="greenbutton">Нет</a>
            </form>
        </div>
{% endblock %}

marks/main/templates/main/delete_favorite.html
{% extends 'main/base.html' %} 

{% block title %}Удаление из избранного{% endblock %}

{% block content %}
<br>
        <h3 class="display-7 fw-normal text-center mb-3">Вы точно хотите удалить этот товар из избранного?</h3>
        <div class="d-flex">
            <form method="post" class="yes_form">
                {% csrf_token %}
                <button class="redbutton" type="submit">Да</button>
                <a href="{% url 'account' %}" style="padding: 10px;" class="greenbutton">Нет</a>
            </form>
        </div>
{% endblock %}

marks/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}
главная
{% endblock %}
{% block content %}

    <h1 class="display-4 fw-normal text-center mt-4">Новости и дропы</h1><br>
    <header></header>
    {% if page %}
        {% for news in page %}
            <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
                <h3>{{ news.news }}</h3><br>
                <img src="{{ news.imagenews.url }}" width="300" height="300"/><br><br>
                <h4 class="fs-5 text-muted">Источник {{ news.source }}</h4><br>
                <a class="pinkbutton my-4" style="padding: 10px; padding-left: 52px; padding-right: 52px;" href="{% url 'news' news.id %}">Комментарии и описание</a>
            </div>
        {% endfor %}
            {% if page.has_previous %}
                <a href="?page=1" class="pinkbutton my-2 mb-2">Первая страница</a>
                <a href="?page={{ page.previous_page_number }}" class="pinkbutton my-2 mb-2">Предыдущщяя</a>
            {% endif %}
            {% if page.has_next %}
                <a href="?page={{ page.next_page_number }}" class="pinkbutton my-2 mb-2">Следующая</a>
                <a href="?page={{ page.paginator.num_pages }}" class="pinkbutton my-2 mb-2">Поледняя страница</a>
            {% endif %}
        <span class="fs-5 text-muted">Страница {{ page.number }} из {{ page.paginator.num_pages }}</span><br><br>
    {% else %}
        <p class="fs-5 text-muted">Да, много сегодня новостей</p>
    {% endif %}
{% endblock %}
{% block content2 %}

{% endblock %}

marks/main/templates/main/order.html
{% extends 'main/base.html' %}

{% block title %}
Order
{% endblock %}

{% block content %}
<br>
  <h1 id="h1" class="display-4 fw-normal text-center">Оформление заказа</h1><br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
      <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
        <h1>{{ yields.name }}</h1>
        <h4 class="fs-5 text-muted">{{ yields.description }}</h4>
        <br>
        <img src="{{ yields.image_1.url }}" width="300" height="300"/><br><br>
        <h4 class="fs-5 text-muted">Укажите свой номер телефона :</h4>
        <p style="max-width: 300px;">{{ form.pnumber }}</p><br>
        <h4 class="fs-5 text-muted">Укажите свой адресс :</h4>
        <p style="max-width: 300px;">{{ form.adress }}</p>
        <button type="submit" class="pinkbutton me-2 mb-2">Заказать</button>
      </div>

        <!-- <button type="submit" class="pinkbutton my-2 mb-2" name="form_type" value="product_form">Добавить</button> -->
    </form>
{% endblock %}

marks/main/templates/main/update.html
{% extends 'main/base.html' %}

{% block title %}
Update
{% endblock %}

{% block content %}
  <h1 id="h1" class="display-4 fw-normal text-center">Редактирование</h1><br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
      <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
        <label for="id_fullname"class="display-7 fw-normal my-4 ">Введите наименование товара:</label>
        <p id="name">{{ form.name }}</p>
        
        <label for="id_pnumber" class="display-7 fw-normal my-4 ">Введите описание товара:</label>
        <p id="description">{{ form.description }}</p>

        <label for="startsdate" class="display-7 fw-normal my-4 ">Введите цену товара:</label>
        <p id="price">{{ form.price }}</p>

        <label for="finishdate" class="display-7 fw-normal my-4 ">Добавте фото:</label>
        <div class="d-flex">
          <p style="min-width: 820px; margin-right: 15px;">{{ form.image_1 }}</p><input type="button" id="add_photo" value="Добавать еще фото" class="form-control" style="max-height: 38px;"/>
        </div>
        <div id="div_photo" class="hidden">
            <p>{{ form.image_2 }}</p>
            <p>{{ form.image_3 }}</p>
            <p>{{ form.image_4 }}</p>
            <p>{{ form.image_5 }}</p>
            <p>{{ form.image_6 }}</p>
        </div>
        {{ error }}
        <h4 class="fs-5 text-muted mb-3">* пожалуйста прикрепляйте картинку в квадратном формате.</h4>

        <button class="greenbutton" type="submit">Обновить</button>
        <a href="{% url 'product-delete' product.id %}" class="redbutton">Удалить продукт</a>
      </div>

        <!-- <button type="submit" class="pinkbutton my-2 mb-2" name="form_type" value="product_form">Добавить</button> -->
    </form>
{% endblock %}